/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Build pack.
 */
export const BuildPack = {
  Nixpacks: "nixpacks",
  Static: "static",
  Dockerfile: "dockerfile",
  Dockercompose: "dockercompose",
} as const;
/**
 * Build pack.
 */
export type BuildPack = ClosedEnum<typeof BuildPack>;

/**
 * How to set redirect with Traefik / Caddy. www<->non-www.
 */
export const Redirect = {
  Www: "www",
  NonWww: "non-www",
  Both: "both",
} as const;
/**
 * How to set redirect with Traefik / Caddy. www<->non-www.
 */
export type Redirect = ClosedEnum<typeof Redirect>;

/**
 * Application model
 */
export type Application = {
  /**
   * The application identifier in the database.
   */
  id?: number | undefined;
  /**
   * The application description.
   */
  description?: string | null | undefined;
  /**
   * The repository project identifier.
   */
  repositoryProjectId?: number | null | undefined;
  /**
   * The application UUID.
   */
  uuid?: string | undefined;
  /**
   * The application name.
   */
  name?: string | undefined;
  /**
   * The application domains.
   */
  fqdn?: string | null | undefined;
  /**
   * Configuration hash.
   */
  configHash?: string | undefined;
  /**
   * Git repository URL.
   */
  gitRepository?: string | undefined;
  /**
   * Git branch.
   */
  gitBranch?: string | undefined;
  /**
   * Git commit SHA.
   */
  gitCommitSha?: string | undefined;
  /**
   * Git full URL.
   */
  gitFullUrl?: string | null | undefined;
  /**
   * Docker registry image name.
   */
  dockerRegistryImageName?: string | null | undefined;
  /**
   * Docker registry image tag.
   */
  dockerRegistryImageTag?: string | null | undefined;
  /**
   * Build pack.
   */
  buildPack?: BuildPack | undefined;
  /**
   * Static image used when static site is deployed.
   */
  staticImage?: string | undefined;
  /**
   * Install command.
   */
  installCommand?: string | undefined;
  /**
   * Build command.
   */
  buildCommand?: string | undefined;
  /**
   * Start command.
   */
  startCommand?: string | undefined;
  /**
   * Ports exposes.
   */
  portsExposes?: string | undefined;
  /**
   * Ports mappings.
   */
  portsMappings?: string | null | undefined;
  /**
   * Base directory for all commands.
   */
  baseDirectory?: string | undefined;
  /**
   * Publish directory.
   */
  publishDirectory?: string | undefined;
  /**
   * Health check enabled.
   */
  healthCheckEnabled?: boolean | undefined;
  /**
   * Health check path.
   */
  healthCheckPath?: string | undefined;
  /**
   * Health check port.
   */
  healthCheckPort?: string | null | undefined;
  /**
   * Health check host.
   */
  healthCheckHost?: string | null | undefined;
  /**
   * Health check method.
   */
  healthCheckMethod?: string | undefined;
  /**
   * Health check return code.
   */
  healthCheckReturnCode?: number | undefined;
  /**
   * Health check scheme.
   */
  healthCheckScheme?: string | undefined;
  /**
   * Health check response text.
   */
  healthCheckResponseText?: string | null | undefined;
  /**
   * Health check interval in seconds.
   */
  healthCheckInterval?: number | undefined;
  /**
   * Health check timeout in seconds.
   */
  healthCheckTimeout?: number | undefined;
  /**
   * Health check retries count.
   */
  healthCheckRetries?: number | undefined;
  /**
   * Health check start period in seconds.
   */
  healthCheckStartPeriod?: number | undefined;
  /**
   * Memory limit.
   */
  limitsMemory?: string | undefined;
  /**
   * Memory swap limit.
   */
  limitsMemorySwap?: string | undefined;
  /**
   * Memory swappiness.
   */
  limitsMemorySwappiness?: number | undefined;
  /**
   * Memory reservation.
   */
  limitsMemoryReservation?: string | undefined;
  /**
   * CPU limit.
   */
  limitsCpus?: string | undefined;
  /**
   * CPU set.
   */
  limitsCpuset?: string | null | undefined;
  /**
   * CPU shares.
   */
  limitsCpuShares?: number | undefined;
  /**
   * Application status.
   */
  status?: string | undefined;
  /**
   * Preview URL template.
   */
  previewUrlTemplate?: string | undefined;
  /**
   * Destination type.
   */
  destinationType?: string | undefined;
  /**
   * Destination identifier.
   */
  destinationId?: number | undefined;
  /**
   * Source identifier.
   */
  sourceId?: number | null | undefined;
  /**
   * Private key identifier.
   */
  privateKeyId?: number | null | undefined;
  /**
   * Environment identifier.
   */
  environmentId?: number | undefined;
  /**
   * Dockerfile content. Used for dockerfile build pack.
   */
  dockerfile?: string | null | undefined;
  /**
   * Dockerfile location.
   */
  dockerfileLocation?: string | undefined;
  /**
   * Custom labels.
   */
  customLabels?: string | null | undefined;
  /**
   * Dockerfile target build.
   */
  dockerfileTargetBuild?: string | null | undefined;
  /**
   * Manual webhook secret for GitHub.
   */
  manualWebhookSecretGithub?: string | null | undefined;
  /**
   * Manual webhook secret for GitLab.
   */
  manualWebhookSecretGitlab?: string | null | undefined;
  /**
   * Manual webhook secret for Bitbucket.
   */
  manualWebhookSecretBitbucket?: string | null | undefined;
  /**
   * Manual webhook secret for Gitea.
   */
  manualWebhookSecretGitea?: string | null | undefined;
  /**
   * Docker compose location.
   */
  dockerComposeLocation?: string | undefined;
  /**
   * Docker compose content. Used for docker compose build pack.
   */
  dockerCompose?: string | null | undefined;
  /**
   * Docker compose raw content.
   */
  dockerComposeRaw?: string | null | undefined;
  /**
   * Docker compose domains.
   */
  dockerComposeDomains?: string | null | undefined;
  /**
   * Docker compose custom start command.
   */
  dockerComposeCustomStartCommand?: string | null | undefined;
  /**
   * Docker compose custom build command.
   */
  dockerComposeCustomBuildCommand?: string | null | undefined;
  /**
   * Swarm replicas. Only used for swarm deployments.
   */
  swarmReplicas?: number | null | undefined;
  /**
   * Swarm placement constraints. Only used for swarm deployments.
   */
  swarmPlacementConstraints?: string | null | undefined;
  /**
   * Custom docker run options.
   */
  customDockerRunOptions?: string | null | undefined;
  /**
   * Post deployment command.
   */
  postDeploymentCommand?: string | null | undefined;
  /**
   * Post deployment command container.
   */
  postDeploymentCommandContainer?: string | null | undefined;
  /**
   * Pre deployment command.
   */
  preDeploymentCommand?: string | null | undefined;
  /**
   * Pre deployment command container.
   */
  preDeploymentCommandContainer?: string | null | undefined;
  /**
   * Watch paths.
   */
  watchPaths?: string | null | undefined;
  /**
   * Custom healthcheck found.
   */
  customHealthcheckFound?: boolean | undefined;
  /**
   * How to set redirect with Traefik / Caddy. www<->non-www.
   */
  redirect?: Redirect | null | undefined;
  /**
   * The date and time when the application was created.
   */
  createdAt?: Date | undefined;
  /**
   * The date and time when the application was last updated.
   */
  updatedAt?: Date | undefined;
  /**
   * The date and time when the application was deleted.
   */
  deletedAt?: Date | null | undefined;
  /**
   * How Coolify parse the compose file.
   */
  composeParsingVersion?: string | undefined;
  /**
   * Custom Nginx configuration base64 encoded.
   */
  customNginxConfiguration?: string | null | undefined;
};

/** @internal */
export const BuildPack$inboundSchema: z.ZodNativeEnum<typeof BuildPack> = z
  .nativeEnum(BuildPack);

/** @internal */
export const BuildPack$outboundSchema: z.ZodNativeEnum<typeof BuildPack> =
  BuildPack$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BuildPack$ {
  /** @deprecated use `BuildPack$inboundSchema` instead. */
  export const inboundSchema = BuildPack$inboundSchema;
  /** @deprecated use `BuildPack$outboundSchema` instead. */
  export const outboundSchema = BuildPack$outboundSchema;
}

/** @internal */
export const Redirect$inboundSchema: z.ZodNativeEnum<typeof Redirect> = z
  .nativeEnum(Redirect);

/** @internal */
export const Redirect$outboundSchema: z.ZodNativeEnum<typeof Redirect> =
  Redirect$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Redirect$ {
  /** @deprecated use `Redirect$inboundSchema` instead. */
  export const inboundSchema = Redirect$inboundSchema;
  /** @deprecated use `Redirect$outboundSchema` instead. */
  export const outboundSchema = Redirect$outboundSchema;
}

/** @internal */
export const Application$inboundSchema: z.ZodType<
  Application,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.number().int().optional(),
  description: z.nullable(z.string()).optional(),
  repository_project_id: z.nullable(z.number().int()).optional(),
  uuid: z.string().optional(),
  name: z.string().optional(),
  fqdn: z.nullable(z.string()).optional(),
  config_hash: z.string().optional(),
  git_repository: z.string().optional(),
  git_branch: z.string().optional(),
  git_commit_sha: z.string().optional(),
  git_full_url: z.nullable(z.string()).optional(),
  docker_registry_image_name: z.nullable(z.string()).optional(),
  docker_registry_image_tag: z.nullable(z.string()).optional(),
  build_pack: z.union([BuildPack$inboundSchema, z.string()]).nullish(),
  static_image: z.string().optional(),
  install_command: z.string().nullish(),
  build_command: z.string().nullish(),
  start_command: z.string().nullish(),
  ports_exposes: z.string().nullish(),
  ports_mappings: z.nullable(z.string()).optional(),
  base_directory: z.string().optional(),
  publish_directory: z.string().nullish(),
  health_check_enabled: z.boolean().optional(),
  health_check_path: z.string().optional(),
  health_check_port: z.nullable(z.string()).optional(),
  health_check_host: z.nullable(z.string()).optional(),
  health_check_method: z.string().optional(),
  health_check_return_code: z.number().int().optional(),
  health_check_scheme: z.string().optional(),
  health_check_response_text: z.nullable(z.string()).optional(),
  health_check_interval: z.number().int().optional(),
  health_check_timeout: z.number().int().optional(),
  health_check_retries: z.number().int().optional(),
  health_check_start_period: z.number().int().optional(),
  limits_memory: z.string().optional(),
  limits_memory_swap: z.string().optional(),
  limits_memory_swappiness: z.number().int().optional(),
  limits_memory_reservation: z.string().optional(),
  limits_cpus: z.string().optional(),
  limits_cpuset: z.nullable(z.string()).optional(),
  limits_cpu_shares: z.number().int().optional(),
  status: z.string().optional(),
  preview_url_template: z.string().optional(),
  destination_type: z.string().optional(),
  destination_id: z.number().int().optional(),
  source_id: z.nullable(z.number().int()).optional(),
  private_key_id: z.nullable(z.number().int()).optional(),
  environment_id: z.number().int().optional(),
  dockerfile: z.nullable(z.string()).optional(),
  dockerfile_location: z.string().nullish(),
  custom_labels: z.nullable(z.string()).optional(),
  dockerfile_target_build: z.nullable(z.string()).optional(),
  manual_webhook_secret_github: z.nullable(z.string()).optional(),
  manual_webhook_secret_gitlab: z.nullable(z.string()).optional(),
  manual_webhook_secret_bitbucket: z.nullable(z.string()).optional(),
  manual_webhook_secret_gitea: z.nullable(z.string()).optional(),
  docker_compose_location: z.string().optional(),
  docker_compose: z.nullable(z.string()).optional(),
  docker_compose_raw: z.nullable(z.string()).optional(),
  docker_compose_domains: z.nullable(z.string()).optional(),
  docker_compose_custom_start_command: z.nullable(z.string()).optional(),
  docker_compose_custom_build_command: z.nullable(z.string()).optional(),
  swarm_replicas: z.nullable(z.number().int()).optional(),
  swarm_placement_constraints: z.nullable(z.string()).optional(),
  custom_docker_run_options: z.nullable(z.string()).optional(),
  post_deployment_command: z.nullable(z.string()).optional(),
  post_deployment_command_container: z.nullable(z.string()).optional(),
  pre_deployment_command: z.nullable(z.string()).optional(),
  pre_deployment_command_container: z.nullable(z.string()).optional(),
  watch_paths: z.nullable(z.string()).optional(),
  custom_healthcheck_found: z.boolean().optional(),
  redirect: z.nullable(Redirect$inboundSchema).optional(),
  created_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  updated_at: z.string().datetime({ offset: true }).transform(v => new Date(v))
    .optional(),
  deleted_at: z.nullable(
    z.string().datetime({ offset: true }).transform(v => new Date(v)),
  ).optional(),
  compose_parsing_version: z.string().optional(),
  custom_nginx_configuration: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    "repository_project_id": "repositoryProjectId",
    "config_hash": "configHash",
    "git_repository": "gitRepository",
    "git_branch": "gitBranch",
    "git_commit_sha": "gitCommitSha",
    "git_full_url": "gitFullUrl",
    "docker_registry_image_name": "dockerRegistryImageName",
    "docker_registry_image_tag": "dockerRegistryImageTag",
    "build_pack": "buildPack",
    "static_image": "staticImage",
    "install_command": "installCommand",
    "build_command": "buildCommand",
    "start_command": "startCommand",
    "ports_exposes": "portsExposes",
    "ports_mappings": "portsMappings",
    "base_directory": "baseDirectory",
    "publish_directory": "publishDirectory",
    "health_check_enabled": "healthCheckEnabled",
    "health_check_path": "healthCheckPath",
    "health_check_port": "healthCheckPort",
    "health_check_host": "healthCheckHost",
    "health_check_method": "healthCheckMethod",
    "health_check_return_code": "healthCheckReturnCode",
    "health_check_scheme": "healthCheckScheme",
    "health_check_response_text": "healthCheckResponseText",
    "health_check_interval": "healthCheckInterval",
    "health_check_timeout": "healthCheckTimeout",
    "health_check_retries": "healthCheckRetries",
    "health_check_start_period": "healthCheckStartPeriod",
    "limits_memory": "limitsMemory",
    "limits_memory_swap": "limitsMemorySwap",
    "limits_memory_swappiness": "limitsMemorySwappiness",
    "limits_memory_reservation": "limitsMemoryReservation",
    "limits_cpus": "limitsCpus",
    "limits_cpuset": "limitsCpuset",
    "limits_cpu_shares": "limitsCpuShares",
    "preview_url_template": "previewUrlTemplate",
    "destination_type": "destinationType",
    "destination_id": "destinationId",
    "source_id": "sourceId",
    "private_key_id": "privateKeyId",
    "environment_id": "environmentId",
    "dockerfile_location": "dockerfileLocation",
    "custom_labels": "customLabels",
    "dockerfile_target_build": "dockerfileTargetBuild",
    "manual_webhook_secret_github": "manualWebhookSecretGithub",
    "manual_webhook_secret_gitlab": "manualWebhookSecretGitlab",
    "manual_webhook_secret_bitbucket": "manualWebhookSecretBitbucket",
    "manual_webhook_secret_gitea": "manualWebhookSecretGitea",
    "docker_compose_location": "dockerComposeLocation",
    "docker_compose": "dockerCompose",
    "docker_compose_raw": "dockerComposeRaw",
    "docker_compose_domains": "dockerComposeDomains",
    "docker_compose_custom_start_command": "dockerComposeCustomStartCommand",
    "docker_compose_custom_build_command": "dockerComposeCustomBuildCommand",
    "swarm_replicas": "swarmReplicas",
    "swarm_placement_constraints": "swarmPlacementConstraints",
    "custom_docker_run_options": "customDockerRunOptions",
    "post_deployment_command": "postDeploymentCommand",
    "post_deployment_command_container": "postDeploymentCommandContainer",
    "pre_deployment_command": "preDeploymentCommand",
    "pre_deployment_command_container": "preDeploymentCommandContainer",
    "watch_paths": "watchPaths",
    "custom_healthcheck_found": "customHealthcheckFound",
    "created_at": "createdAt",
    "updated_at": "updatedAt",
    "deleted_at": "deletedAt",
    "compose_parsing_version": "composeParsingVersion",
    "custom_nginx_configuration": "customNginxConfiguration",
  });
});

/** @internal */
export type Application$Outbound = {
  id?: number | undefined;
  description?: string | null | undefined;
  repository_project_id?: number | null | undefined;
  uuid?: string | undefined;
  name?: string | undefined;
  fqdn?: string | null | undefined;
  config_hash?: string | undefined;
  git_repository?: string | undefined;
  git_branch?: string | undefined;
  git_commit_sha?: string | undefined;
  git_full_url?: string | null | undefined;
  docker_registry_image_name?: string | null | undefined;
  docker_registry_image_tag?: string | null | undefined;
  build_pack?: string | undefined;
  static_image?: string | undefined;
  install_command?: string | undefined;
  build_command?: string | undefined;
  start_command?: string | undefined;
  ports_exposes?: string | undefined;
  ports_mappings?: string | null | undefined;
  base_directory?: string | undefined;
  publish_directory?: string | undefined;
  health_check_enabled?: boolean | undefined;
  health_check_path?: string | undefined;
  health_check_port?: string | null | undefined;
  health_check_host?: string | null | undefined;
  health_check_method?: string | undefined;
  health_check_return_code?: number | undefined;
  health_check_scheme?: string | undefined;
  health_check_response_text?: string | null | undefined;
  health_check_interval?: number | undefined;
  health_check_timeout?: number | undefined;
  health_check_retries?: number | undefined;
  health_check_start_period?: number | undefined;
  limits_memory?: string | undefined;
  limits_memory_swap?: string | undefined;
  limits_memory_swappiness?: number | undefined;
  limits_memory_reservation?: string | undefined;
  limits_cpus?: string | undefined;
  limits_cpuset?: string | null | undefined;
  limits_cpu_shares?: number | undefined;
  status?: string | undefined;
  preview_url_template?: string | undefined;
  destination_type?: string | undefined;
  destination_id?: number | undefined;
  source_id?: number | null | undefined;
  private_key_id?: number | null | undefined;
  environment_id?: number | undefined;
  dockerfile?: string | null | undefined;
  dockerfile_location?: string | undefined;
  custom_labels?: string | null | undefined;
  dockerfile_target_build?: string | null | undefined;
  manual_webhook_secret_github?: string | null | undefined;
  manual_webhook_secret_gitlab?: string | null | undefined;
  manual_webhook_secret_bitbucket?: string | null | undefined;
  manual_webhook_secret_gitea?: string | null | undefined;
  docker_compose_location?: string | undefined;
  docker_compose?: string | null | undefined;
  docker_compose_raw?: string | null | undefined;
  docker_compose_domains?: string | null | undefined;
  docker_compose_custom_start_command?: string | null | undefined;
  docker_compose_custom_build_command?: string | null | undefined;
  swarm_replicas?: number | null | undefined;
  swarm_placement_constraints?: string | null | undefined;
  custom_docker_run_options?: string | null | undefined;
  post_deployment_command?: string | null | undefined;
  post_deployment_command_container?: string | null | undefined;
  pre_deployment_command?: string | null | undefined;
  pre_deployment_command_container?: string | null | undefined;
  watch_paths?: string | null | undefined;
  custom_healthcheck_found?: boolean | undefined;
  redirect?: string | null | undefined;
  created_at?: string | undefined;
  updated_at?: string | undefined;
  deleted_at?: string | null | undefined;
  compose_parsing_version?: string | undefined;
  custom_nginx_configuration?: string | null | undefined;
};

/** @internal */
export const Application$outboundSchema: z.ZodType<
  Application$Outbound,
  z.ZodTypeDef,
  Application
> = z.object({
  id: z.number().int().optional(),
  description: z.nullable(z.string()).optional(),
  repositoryProjectId: z.nullable(z.number().int()).optional(),
  uuid: z.string().optional(),
  name: z.string().optional(),
  fqdn: z.nullable(z.string()).optional(),
  configHash: z.string().optional(),
  gitRepository: z.string().optional(),
  gitBranch: z.string().optional(),
  gitCommitSha: z.string().optional(),
  gitFullUrl: z.nullable(z.string()).optional(),
  dockerRegistryImageName: z.nullable(z.string()).optional(),
  dockerRegistryImageTag: z.nullable(z.string()).optional(),
  buildPack: BuildPack$outboundSchema.optional(),
  staticImage: z.string().optional(),
  installCommand: z.string().optional(),
  buildCommand: z.string().optional(),
  startCommand: z.string().optional(),
  portsExposes: z.string().optional(),
  portsMappings: z.nullable(z.string()).optional(),
  baseDirectory: z.string().optional(),
  publishDirectory: z.string().optional(),
  healthCheckEnabled: z.boolean().optional(),
  healthCheckPath: z.string().optional(),
  healthCheckPort: z.nullable(z.string()).optional(),
  healthCheckHost: z.nullable(z.string()).optional(),
  healthCheckMethod: z.string().optional(),
  healthCheckReturnCode: z.number().int().optional(),
  healthCheckScheme: z.string().optional(),
  healthCheckResponseText: z.nullable(z.string()).optional(),
  healthCheckInterval: z.number().int().optional(),
  healthCheckTimeout: z.number().int().optional(),
  healthCheckRetries: z.number().int().optional(),
  healthCheckStartPeriod: z.number().int().optional(),
  limitsMemory: z.string().optional(),
  limitsMemorySwap: z.string().optional(),
  limitsMemorySwappiness: z.number().int().optional(),
  limitsMemoryReservation: z.string().optional(),
  limitsCpus: z.string().optional(),
  limitsCpuset: z.nullable(z.string()).optional(),
  limitsCpuShares: z.number().int().optional(),
  status: z.string().optional(),
  previewUrlTemplate: z.string().optional(),
  destinationType: z.string().optional(),
  destinationId: z.number().int().optional(),
  sourceId: z.nullable(z.number().int()).optional(),
  privateKeyId: z.nullable(z.number().int()).optional(),
  environmentId: z.number().int().optional(),
  dockerfile: z.nullable(z.string()).optional(),
  dockerfileLocation: z.string().optional(),
  customLabels: z.nullable(z.string()).optional(),
  dockerfileTargetBuild: z.nullable(z.string()).optional(),
  manualWebhookSecretGithub: z.nullable(z.string()).optional(),
  manualWebhookSecretGitlab: z.nullable(z.string()).optional(),
  manualWebhookSecretBitbucket: z.nullable(z.string()).optional(),
  manualWebhookSecretGitea: z.nullable(z.string()).optional(),
  dockerComposeLocation: z.string().optional(),
  dockerCompose: z.nullable(z.string()).optional(),
  dockerComposeRaw: z.nullable(z.string()).optional(),
  dockerComposeDomains: z.nullable(z.string()).optional(),
  dockerComposeCustomStartCommand: z.nullable(z.string()).optional(),
  dockerComposeCustomBuildCommand: z.nullable(z.string()).optional(),
  swarmReplicas: z.nullable(z.number().int()).optional(),
  swarmPlacementConstraints: z.nullable(z.string()).optional(),
  customDockerRunOptions: z.nullable(z.string()).optional(),
  postDeploymentCommand: z.nullable(z.string()).optional(),
  postDeploymentCommandContainer: z.nullable(z.string()).optional(),
  preDeploymentCommand: z.nullable(z.string()).optional(),
  preDeploymentCommandContainer: z.nullable(z.string()).optional(),
  watchPaths: z.nullable(z.string()).optional(),
  customHealthcheckFound: z.boolean().optional(),
  redirect: z.nullable(Redirect$outboundSchema).optional(),
  createdAt: z.date().transform(v => v.toISOString()).optional(),
  updatedAt: z.date().transform(v => v.toISOString()).optional(),
  deletedAt: z.nullable(z.date().transform(v => v.toISOString())).optional(),
  composeParsingVersion: z.string().optional(),
  customNginxConfiguration: z.nullable(z.string()).optional(),
}).transform((v) => {
  return remap$(v, {
    repositoryProjectId: "repository_project_id",
    configHash: "config_hash",
    gitRepository: "git_repository",
    gitBranch: "git_branch",
    gitCommitSha: "git_commit_sha",
    gitFullUrl: "git_full_url",
    dockerRegistryImageName: "docker_registry_image_name",
    dockerRegistryImageTag: "docker_registry_image_tag",
    buildPack: "build_pack",
    staticImage: "static_image",
    installCommand: "install_command",
    buildCommand: "build_command",
    startCommand: "start_command",
    portsExposes: "ports_exposes",
    portsMappings: "ports_mappings",
    baseDirectory: "base_directory",
    publishDirectory: "publish_directory",
    healthCheckEnabled: "health_check_enabled",
    healthCheckPath: "health_check_path",
    healthCheckPort: "health_check_port",
    healthCheckHost: "health_check_host",
    healthCheckMethod: "health_check_method",
    healthCheckReturnCode: "health_check_return_code",
    healthCheckScheme: "health_check_scheme",
    healthCheckResponseText: "health_check_response_text",
    healthCheckInterval: "health_check_interval",
    healthCheckTimeout: "health_check_timeout",
    healthCheckRetries: "health_check_retries",
    healthCheckStartPeriod: "health_check_start_period",
    limitsMemory: "limits_memory",
    limitsMemorySwap: "limits_memory_swap",
    limitsMemorySwappiness: "limits_memory_swappiness",
    limitsMemoryReservation: "limits_memory_reservation",
    limitsCpus: "limits_cpus",
    limitsCpuset: "limits_cpuset",
    limitsCpuShares: "limits_cpu_shares",
    previewUrlTemplate: "preview_url_template",
    destinationType: "destination_type",
    destinationId: "destination_id",
    sourceId: "source_id",
    privateKeyId: "private_key_id",
    environmentId: "environment_id",
    dockerfileLocation: "dockerfile_location",
    customLabels: "custom_labels",
    dockerfileTargetBuild: "dockerfile_target_build",
    manualWebhookSecretGithub: "manual_webhook_secret_github",
    manualWebhookSecretGitlab: "manual_webhook_secret_gitlab",
    manualWebhookSecretBitbucket: "manual_webhook_secret_bitbucket",
    manualWebhookSecretGitea: "manual_webhook_secret_gitea",
    dockerComposeLocation: "docker_compose_location",
    dockerCompose: "docker_compose",
    dockerComposeRaw: "docker_compose_raw",
    dockerComposeDomains: "docker_compose_domains",
    dockerComposeCustomStartCommand: "docker_compose_custom_start_command",
    dockerComposeCustomBuildCommand: "docker_compose_custom_build_command",
    swarmReplicas: "swarm_replicas",
    swarmPlacementConstraints: "swarm_placement_constraints",
    customDockerRunOptions: "custom_docker_run_options",
    postDeploymentCommand: "post_deployment_command",
    postDeploymentCommandContainer: "post_deployment_command_container",
    preDeploymentCommand: "pre_deployment_command",
    preDeploymentCommandContainer: "pre_deployment_command_container",
    watchPaths: "watch_paths",
    customHealthcheckFound: "custom_healthcheck_found",
    createdAt: "created_at",
    updatedAt: "updated_at",
    deletedAt: "deleted_at",
    composeParsingVersion: "compose_parsing_version",
    customNginxConfiguration: "custom_nginx_configuration",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Application$ {
  /** @deprecated use `Application$inboundSchema` instead. */
  export const inboundSchema = Application$inboundSchema;
  /** @deprecated use `Application$outboundSchema` instead. */
  export const outboundSchema = Application$outboundSchema;
  /** @deprecated use `Application$Outbound` instead. */
  export type Outbound = Application$Outbound;
}

export function applicationToJSON(application: Application): string {
  return JSON.stringify(Application$outboundSchema.parse(application));
}

export function applicationFromJSON(
  jsonString: string,
): SafeParseResult<Application, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Application$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Application' from JSON`,
  );
}
